# Generated by Django 5.2 on 2025-04-19 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Announcement', max_length=200)),
                ('content', models.TextField(default='No content.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('email', models.EmailField(default='not_provided@example.com', max_length=254)),
                ('message', models.TextField(default='No message provided.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(default='N/A', max_length=20)),
                ('subject_name', models.CharField(default='Unnamed Subject', max_length=100)),
                ('schedule', models.CharField(default='TBA', max_length=50)),
                ('duration', models.IntegerField(default=60)),
                ('room', models.CharField(default='Room 1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=255)),
                ('middle_name', models.CharField(default=' ', max_length=255)),
                ('last_name', models.CharField(default=' ', max_length=255)),
                ('email', models.EmailField(default='not_provided@example.com', max_length=254)),
                ('contact_number', models.CharField(default='0000000000', max_length=15)),
                ('previous_school', models.CharField(default='Unknown School', max_length=255)),
                ('house_number', models.CharField(default=' ', max_length=100)),
                ('street_name', models.CharField(default=' ', max_length=255)),
                ('barangay', models.CharField(default=' ', max_length=255)),
                ('city_municipality', models.CharField(default=' ', max_length=255)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='Philippines', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Status of the application (Pending, Accepted, Rejected)', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['application_date'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(default='N/A', max_length=20)),
                ('subject_name', models.CharField(default='Unnamed Class', max_length=100)),
                ('schedule', models.CharField(default='TBA', max_length=100)),
                ('duration', models.IntegerField(default=60)),
                ('room', models.CharField(default='Room 1', max_length=50)),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Untitled Course', max_length=255)),
                ('grade', models.CharField(default='N/A', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unnamed Student', max_length=255)),
                ('email', models.EmailField(default='student@example.com', max_length=254)),
                ('contact_number', models.CharField(default='0000000000', max_length=15)),
                ('previous_school', models.CharField(default='Unknown School', max_length=255)),
                ('address', models.TextField(default='No Address Provided')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('generated_password', models.CharField(blank=True, default='password123', max_length=128, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='No First Name', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(default='Not Provided')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
                ('students', models.ManyToManyField(related_name='student_classes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacherprofile')),
            ],
        ),
    ]
