# Generated by Django 5.2 on 2025-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='generated_password',
            field=models.CharField(blank=True, default='samplepassword', max_length=128, null=True),
        ),
    ]
