# Generated by Django 5.2 on 2025-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_class_subject_delete_studentgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='cashier_payment_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/payment/'),
        ),
        migrations.AddField(
            model_name='student',
            name='certificate_of_good_moral_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/good_moral/'),
        ),
        migrations.AddField(
            model_name='student',
            name='form_138_137_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/form_138/'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_pictures_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_pictures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='long_envelopes_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/long_envelopes/'),
        ),
        migrations.AddField(
            model_name='student',
            name='psa_birth_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/psa_birth/'),
        ),
        migrations.AddField(
            model_name='student',
            name='psa_marriage_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/psa_marriage/'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_form_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/registration_form/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_school',
            field=models.CharField(default='', max_length=255),
        ),
    ]
