# Generated by Django 5.2 on 2025-04-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_generated_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.AddField(
            model_name='class',
            name='prerequisite',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject_code',
            field=models.CharField(default='ex: SHSCO 01', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject_name',
            field=models.CharField(default='ex: Oral Communication', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='prerequisite',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
