# Generated by Django 5.2 on 2025-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_class_schedule_class_prerequisite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('classes', models.ManyToManyField(related_name='groups', to='myapp.class')),
            ],
        ),
    ]
