# Generated by Django 5.2 on 2025-05-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_class_subject_student_cashier_payment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='finals',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='midterm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='pre_finals',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='prelims',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
