# Generated by Django 5.2 on 2025-04-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_classgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='strand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='level',
            field=models.CharField(choices=[('highschool', 'High School'), ('college', 'College')], default='High School', max_length=10),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='strand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
