# Generated by Django 5.2 on 2025-05-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_grade_grade_grade_finals_grade_midterm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='pre_finals',
            new_name='prefinals',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='prelims',
            new_name='prelim',
        ),
    ]
