# Generated by Django 5.2 on 2025-04-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_application_strand_classgroup_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='academic_year',
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='level',
            field=models.CharField(choices=[('HS11', 'Senior High School Grade 11'), ('HS12', 'Senior High School Grade 12'), ('COL', 'College')], default='HS11', max_length=4),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='strand',
            field=models.CharField(choices=[('ABM', 'ABM'), ('GAS', 'GAS'), ('HUMMS', 'HUMMS'), ('HRM', 'HRM'), ('TM', 'Tourism Management'), ('ICT', 'Information and Communication Technology')], default='GAS', max_length=10),
        ),
    ]
