# Generated by Django 5.2 on 2025-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_pre_finals_grade_prefinals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='suffix',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
