# Generated by Django 5.2 on 2025-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_application_guardian_name_application_suffix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='form_138_137',
            new_name='form_137',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form_138_137_file',
            new_name='form_137_file',
        ),
        migrations.AddField(
            model_name='student',
            name='form_138',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='form_138_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/form_138/'),
        ),
    ]
