# Generated by Django 5.2 on 2025-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_application_strand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='level',
            field=models.CharField(choices=[('HS11', 'High School Grade 11'), ('HS12', 'High School Grade 12'), ('COL', 'College')], default='HS11', help_text='Level of the student (HS11, HS12, COL)', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='strand',
            field=models.CharField(choices=[('ABM', 'ABM'), ('GAS', 'GAS'), ('HUMMS', 'HUMMS'), ('HRM', 'HRM'), ('TM', 'TM'), ('ICT', 'ICT')], default='GAS', help_text='Strand for which the student is applying', max_length=10),
        ),
    ]
