# Generated by Django 5.2 on 2025-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_application_level_application_strand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Academic Period',
                'verbose_name_plural': 'Academic Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='school_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
    ]
