# Generated by Django 5.2 on 2025-04-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_academicperiod_classgroup_school_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicPeriod',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='school_year',
        ),
        migrations.AddField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
