# Generated by Django 5.2 on 2025-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_academicperiod_remove_classgroup_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cashier_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='certificate_of_good_moral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='form_138_137',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='id_pictures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='long_envelopes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='psa_birth_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='psa_marriage_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_form',
            field=models.BooleanField(default=False),
        ),
    ]
