# Generated by Django 5.2 on 2025-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_student_cashier_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='strand',
            field=models.CharField(default='GAS', max_length=100),
            preserve_default=False,
        ),
    ]
