# Generated by Django 5.2 on 2025-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_groups', to='myapp.student'),
        ),
    ]
