# Generated by Django 5.2 on 2025-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
