# Generated by Django 5.2 on 2025-04-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_announcement_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.AddField(
            model_name='application',
            name='barangay',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='city_municipality',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='house_number',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='middle_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='street_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_school',
            field=models.CharField(max_length=255),
        ),
    ]
