# Generated by Django 5.2 on 2025-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_application_address_remove_application_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.AlterField(
            model_name='class',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
