# Generated by Django 5.2 on 2025-04-19 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_class_students_class_teacher_alter_class_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='subject',
            name='room',
            field=models.CharField(default='Room 1', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='schedule',
            field=models.CharField(default='TBA', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='Unnamed Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(default='No content.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Untitled Announcement', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='country',
            field=models.CharField(default='Philippines', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_school',
            field=models.CharField(default='Unknown School', max_length=255),
        ),
        migrations.AlterField(
            model_name='class',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='class',
            name='room',
            field=models.CharField(default='Room 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.CharField(default='TBA', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject_code',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject_name',
            field=models.CharField(default='Unnamed Class', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default='No message provided.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course_name',
            field=models.CharField(default='Untitled Course', max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='first_name',
            field=models.CharField(default='No First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unnamed Student', max_length=255)),
                ('email', models.EmailField(default='student@example.com', max_length=254)),
                ('contact_number', models.CharField(default='0000000000', max_length=15)),
                ('previous_school', models.CharField(default='Unknown School', max_length=255)),
                ('address', models.TextField(default='No Address Provided')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('generated_password', models.CharField(blank=True, default='password123', max_length=128, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
